In [4]:
import numpy as np

a=np.arange(12)
print(a)
a=a.reshape(3,4)
print(a)
#a=a.reshape(5,3)
#print(a)
a=a.reshape(2,-1)
print(a)
a=a.reshape(-1,3)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [6]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
a=a.reshape(-1)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [7]:
a=np.arange(12).reshape(2,3,2)
print(a)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [8]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[1])
print(a[-3])
print(a[2:6])
print(a[-1:-5:-1])

2
7
[3 4 5 6]
[9 8 7 6]


In [9]:
a=np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [10]:
print(a[1:3,2:4])

[[ 6  7]
 [10 11]]


In [12]:
print(a[1,2:4])

[6 7]


In [13]:
print(a[0:2,1])

[1 5]


In [14]:
print(a[0:2,1:2])

[[1]
 [5]]


In [17]:
print(a[0,1])

1


In [18]:
print(a[[0,2],1:3])

[[ 1  2]
 [ 9 10]]


In [20]:
print(a,a[[0,2],[1,2]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] [ 1 10]


In [21]:
print(a[-1::-1,1::-1])

[[9 8]
 [5 4]
 [1 0]]


In [22]:
print(a[-1::-1])

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [23]:
a=np.arange(24).reshape(3,4,2)
print(a)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


In [24]:
print(a[1:3,1:2,0:2])

[[[10 11]]

 [[18 19]]]


In [27]:
print(a[1:3][:,:,1])

[[ 9 11 13 15]
 [17 19 21 23]]


In [28]:
print(a[1:3][:,1,:])

[[10 11]
 [18 19]]


In [32]:
print(a[[0,2],1:3,-1:0:-1])

[[[ 3]
  [ 5]]

 [[19]
  [21]]]


In [33]:
print(a[[0],1:3,-1:0:-1])

[[[3]
  [5]]]


In [34]:
print(a[[0],1:3,-1:0:-1].shape)

(1, 2, 1)


In [35]:
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [39]:
a=np.ones((4,5),dtype=int)
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [38]:
a=np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [52]:
a=np.random.rand()
print(a)
a=np.random.random((4,3))
print(a)
a=np.random.randint(5,25,size=(3,3))
print(a)
a=np.random.choice(["Rock","Paper","Scisors"])
print(a)

0.7590074332884396
[[0.34533772 0.27219767 0.68722282]
 [0.752685   0.49188967 0.69650281]
 [0.39261234 0.02182909 0.43758981]
 [0.14889897 0.14331068 0.63787427]]
[[ 9  7 16]
 [17  9  8]
 [23 18 13]]
Paper


In [53]:
a=np.arange(12).reshape(3,4)
b=np.arange(6,18).reshape(3,4)
print(a)
print(a+2)
print(a-3)
print(a*2)
print(a/3)
print(a==4)
print(a>5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[-3 -2 -1  0]
 [ 1  2  3  4]
 [ 5  6  7  8]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[0.         0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.         2.33333333]
 [2.66666667 3.         3.33333333 3.66666667]]
[[False False False False]
 [ True False False False]
 [False False False False]]
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


In [54]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a>b)
print(a<b)
print(a==b)

[[ 6  8 10 12]
 [14 16 18 20]
 [22 24 26 28]]
[[-6 -6 -6 -6]
 [-6 -6 -6 -6]
 [-6 -6 -6 -6]]
[[  0   7  16  27]
 [ 40  55  72  91]
 [112 135 160 187]]
[[0.         0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5        0.53846154]
 [0.57142857 0.6        0.625      0.64705882]]
[[False False False False]
 [False False False False]
 [False False False False]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False False]
 [False False False False]
 [False False False False]]


In [55]:
a=np.arange(12).reshape(3,4)
b=np.arange(6,18).reshape(4,3)
print(np.dot(a,b))

[[ 78  84  90]
 [246 268 290]
 [414 452 490]]


In [56]:
a=np.array([1,2,3,6,4,7,5,8,1])
print(np.where(a==3))

(array([2], dtype=int64),)


In [57]:
a=np.array([1,2,3,6,4,7,5,8,1])
print(np.where(a>5))

(array([3, 5, 7], dtype=int64),)


In [59]:
a=np.array([[1,2,3],[3,5,3],[7,3,4]])
print(a)
print(np.where(a==3))

[[1 2 3]
 [3 5 3]
 [7 3 4]]
(array([0, 1, 1, 2], dtype=int64), array([2, 0, 2, 1], dtype=int64))


In [60]:
a=np.array([[[1,2],[3,4],[2,4]],[[3,5],[4,2],[1,4]]])
print(a)
print(np.where(a==4))

[[[1 2]
  [3 4]
  [2 4]]

 [[3 5]
  [4 2]
  [1 4]]]
(array([0, 0, 1, 1], dtype=int64), array([1, 2, 1, 2], dtype=int64), array([1, 1, 0, 1], dtype=int64))


In [ ]:
import numpy as np

class GuessingGame:
    n=0
    a=0
    d=0
    def __init__(self,n,a,d):
        self.n=n
        self.a=a
        self.d=d
        self.start()
    def start(self):
        print("Start Guessing : ")
        while self.a>0:
            i = self.accept()
            self.validate(i)
            if i==self.n:
                print("You win!!!")
                return
            self.a=self.a-1
        print("You lose!!!")  
        print("Number was ",self.n)
    def accept(self):
        return int(input("Enter your guess : "))
    def validate(self,i):
        if i==self.n:
            self.display("Correct guess")
        elif i>self.n:
            self.display("Too high")
        elif i<self.n:
            self.display("Too low")
    def display(self,p):
        print(p)

print("Start Guessing Game : ")
d = int(input("Choose Difficulty : 1=Easy / 2=Hard : "))

if d==1 :
    n = np.random.randint(0,100)
    a = 6
    g = GuessingGame(n,a,d)
elif d==2 :
    n = np.random.randint(0,1000)
    a = 9
    g = GuessingGame(n,a,d)
else :
    print("Input is Invalid")
    

Start Guessing Game : 
Choose Difficulty : 1=Easy / 2=Hard : 1
Start Guessing : 
Enter your guess : 50
Too low
Enter your guess : 75
Too low
Enter your guess : 85
Too high
