In [3]:
import numpy as np

a1=np.array([1,2,3,5,2,1,4,6,2])
a2=np.array([[12,23,33],[21,45,21],[17,33,28]])
print(np.sort(a1))
print(np.sort(a2))
print(np.sort(a2,axis=0))

[1 1 2 2 2 3 4 5 6]
[[12 23 33]
 [21 21 45]
 [17 28 33]]
[[12 23 21]
 [17 33 28]
 [21 45 33]]


In [6]:
a1=np.array([[[2,3],[4,2],[1,5]],[[1,5],[3,6],[7,9]]])
print(a1)
print(np.sort(a1,axis=0))
print(np.sort(a1,axis=1))

[[[2 3]
  [4 2]
  [1 5]]

 [[1 5]
  [3 6]
  [7 9]]]
[[[1 3]
  [3 2]
  [1 5]]

 [[2 5]
  [4 6]
  [7 9]]]
[[[1 2]
  [2 3]
  [4 5]]

 [[1 5]
  [3 6]
  [7 9]]]


In [7]:
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)
print(a)
print(b)
print(np.concatenate((a,b),axis=0))

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [9]:
a=np.arange(18).reshape(3,2,3)
b=np.arange(18,36).reshape(3,2,3)
print(a)
print(b)
print(np.concatenate((a,b),axis=0))
print(np.concatenate((a,b),axis=1))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
[[[18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]]]
[[[ 0  1  2]
  [ 3  4  5]
  [18 19 20]
  [21 22 23]]

 [[ 6  7  8]
  [ 9 10 11]
  [24 25 26]
  [27 28 29]]

 [[12 13 14]
  [15 16 17]
  [30 31 32]
  [33 34 35]]]


In [21]:
a=np.array([1,2,3,4,5,6])
print(np.array_split(a,3))
a=np.arange(6).reshape(3,2)
print(np.array_split(a,3,axis=1))
print(np.array_split(a,4,axis=1))
a=np.arange(18).reshape(2,3,3)
print(a)
print(np.array_split(a,3,axis=1))
print(np.array_split(a,3,axis=1)[1].shape[2])

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([[0],
       [2],
       [4]]), array([[1],
       [3],
       [5]]), array([], shape=(3, 0), dtype=int32)]
[array([[0],
       [2],
       [4]]), array([[1],
       [3],
       [5]]), array([], shape=(3, 0), dtype=int32), array([], shape=(3, 0), dtype=int32)]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
[array([[[ 0,  1,  2]],

       [[ 9, 10, 11]]]), array([[[ 3,  4,  5]],

       [[12, 13, 14]]]), array([[[ 6,  7,  8]],

       [[15, 16, 17]]])]
3


In [2]:
# Create a class called Matrix containing constructor that initialized the number of rows and number of columns of a new 
# Matrix object.

# The Matrix class has methods for each of the following:
# 1. get the number of rows
# 2. get the number of columns
# 3. set the elements of the matrix at given position (i,j)
# 4. adding two matrices. If the matrices are not addable, “ Matrices cannot be added” will be displayed.
# (Overload the addition operation to perform this)
# 5. Multiplying the two matrices.  If the matrices are not multiplied, “ Matrices cannot be multiplied” will 
# be displayed.(Overload the addition operation to perform this)

import numpy as np

class Matrix:
    def __init__(self,r,c):
        self.rows=r
        self.cols=c
        
    def getRows(self):
        return self.rows
    
    def getCols(self):
        return self.cols
    
    def setElements(self):
        self.arr = np.zeros((self.rows,self.cols),dtype=int)
        k = 0
        for i in range(self.rows):
            for j in range(self.cols):
                k+=1
                el = int(input(f"Enter element {k} :"))
                self.arr[i][j]=el
                
    def __add__(self,other):
        if self.arr.shape==other.arr.shape:
            return self.arr+other.arr
        else:
            return "Matrics cannot be added"
        
    def __mul__(self,other):
        if self.rows==other.cols:
            return np.dot(self.arr,other.arr)
        else:
            return "Matrics cannot be multiplied"
        
a = Matrix(2,2)
a.setElements()
b = Matrix(2,2)
b.setElements()
print(a+b)
print(a*b)

Enter element 1 :2
Enter element 2 :1
Enter element 3 :2
Enter element 4 :1
Enter element 1 :2
Enter element 2 :1
Enter element 3 :2
Enter element 4 :1
[[4 2]
 [4 2]]
[[6 3]
 [6 3]]
