In [6]:
import numpy as np

a=np.array([[[1,2],[3,2]],[[2,4],[5,6]]])
x=np.array_split(a,25,axis=1)
print(x[4][0,1:2,0:1])

[]


In [7]:
class A:
    pass
class B:
    pass
class C(A,B):
    pass
class P(C,A):
    pass
class Q(C,B):
    pass
class R(A):
    pass
class X(Q,P,R):
    pass
print(X.mro())

[<class '__main__.X'>, <class '__main__.Q'>, <class '__main__.P'>, <class '__main__.C'>, <class '__main__.R'>, <class '__main__.A'>, <class '__main__.B'>, <class 'object'>]


In [ ]:
# Problem Definition: Sales Stability & Risk Assessment System
# 1. Scenario
# A multinational retail corporation tracks its inventory performance across different geographical regions. The
# data is stored in a 3D NumPy array of shape (6, 5, 2), where:
#  Axis 0: Represents 6 Products.
#  Axis 1: Represents 5 Regions.
#  Axis 2: Represents 2 Metrics (Index 0: Total Units Sold, Index 1: Units Returned).
# You are required to build an analytics engine using Single Inheritance to evaluate product stability and identify
# operational risks.
# sales = np.array([
#  [[120,10], [140,12], [130,11], [150,13], [135,10]],
#  [[80,15], [90,18], [85,16], [88,17], [92,19]],
#  [[200,8], [210,9], [205,10], [215,8], [220,7]],
#  [[60,20], [65,22], [70,21], [68,23], [72,24]],
#  [[150,12], [155,13], [148,14], [160,15], [158,12]],
#  [[230,6], [240,7], [235,6], [245,8], [250,7]]
# ])

# 2. Class Structure
# A. Base Class: BaseSalesData
#  Purpose: To initialize the core data and store basic array dimensions.
#  Attributes: sales (3D Array), products (Integer), and regions (Integer).
# B. Derived Class: SalesStabilityAnalysis
#  Inheritance: Inherits from BaseSalesData.
#  Purpose: Implements logic for net sales, stability indexing, and priority planning.
# 3. SalesStabilityAnalysis methods: Functional Requirements & Return Types
# Method Name ObjecƟve Logic / Criteria Output Return
# Data Type
# net_units() Calculate actual
# sales. Subtract Returns from Units Sold.
# NumPy Array
# (2D)
# risk_products() IdenƟfy high-return
# items.
# Returns > 15 in any region. List
# Method Name ObjecƟve Logic / Criteria Output Return
# Data Type
# regional_reliability() Measure region
# performance. Average net units per region. List
# most_stable_product() Find consistent
# performers. Highest minimum net units. Integer
# normalize_returns() Data Cleaning. Cap returns between 14-16 at 14.
# NumPy Array
# (2D)
# stability_index() Performance Scoring. Divide the average net units by 200 and
# then mulƟply the result by 100 List
# forecast_readiness() Categorical Status.
# High, Moderate, Low, or Unstable.
# Label as High (>75), Moderate (>60),
# Low (>50), or Unstable (<50).
# List
# planning_priority() Strategy Ranking. Product IDs sorted by Stability. List
# Note: For proper execution and correct output generation, it is mandatory to include the following code in your
# program.
# sa = SalesStabilityAnalysis(sales)
# print("Net Units:\n", sa.net_units())
# print("Risk Products:", sa.risk_products())
# print("Regional Reliability:", sa.regional_reliability())
# print("Most Stable Product ID:", sa.most_stable_product())
# print("AŌer Return NormalizaƟon:\n", sa.normalize_returns())
# print("Stability Index:", sa.stability_index())
# print("Forecast Readiness:", sa.forecast_readiness())
# print("Planning Priority:", sa.planning_priority()) 

In [26]:
import numpy as np

sales = np.array([
 [[120,10], [140,12], [130,11], [150,13], [135,10]],
 [[80,15], [90,18], [85,16], [88,17], [92,19]],
 [[200,8], [210,9], [205,10], [215,8], [220,7]],
 [[60,20], [65,22], [70,21], [68,23], [72,24]],
 [[150,12], [155,13], [148,14], [160,15], [158,12]],
 [[230,6], [240,7], [235,6], [245,8], [250,7]]
]) 

class BaseSalesData:
    def __init__(self,sales):
        self.sales=sales
        self.products=self.sales.shape[0]
        self.regions=self.sales.shape[1]
    
class SalesStabilityAnalysis(BaseSalesData):
    def net_units(self):
        net=[]
        for p in range(self.products):
            row=[]
            for r in range(self.regions):
                row.append(self.sales[p][r][0]-self.sales[p][r][1])
            net.append(row)
        return np.array(net)
    def risk_products(self):
        risky=[]
        for p in range(self.products):
            for r in range(self.regions):
                if self.sales[p][r][1]>15:
                    risky.append(p)
                    break
        return risky  
    def regional_reliability(self):
        net=self.net_units()
        avg=[]
        for r in range(self.regions):
            s=0
            for p in range(self.products):
                s+=net[p][r]
            avg.append(s/self.products)
        return avg    
    def most_stable_product(self):
        net=self.net_units()
        min_values=[]
        for p in range(self.products):
            min_values.append(np.min(net[p]))
        return np.argmax(min_values)    
    def normalize_returns(self):
        for p in range(self.products):
            for r in range(self.regions):
                if 14<self.sales[p][r][1]<=16:
                    self.sales[p][r][1]=14
        return self.net_units()            
    def stability_index(self):
        net=self.net_units()
        index=[]
        for p in range(self.products):
            total=0
            for r in range(self.regions):
                total+=net[p][r]
            avg=total/self.regions
            index.append((avg/200)*100)
        return index    
    def forecast_readiness(self):
        index=self.stability_index()
        status=[]
        for i in index:
            if i>=75:
                status.append("High")
            elif i>=60:
                status.append("Moderate")
            elif i>=50:
                status.append("Low")
            else:
                status.append("Unstable")
        return status        
    def planning_priority(self):
        index=self.stability_index()
        temp=list(enumerate(index))
        temp.sort(key=lambda x:x[1],reverse=True)
        order=[]
        for i in temp:
            order.append(i[0])
        return order    
        
sa = SalesStabilityAnalysis(sales)
print("Net Units:",sa.net_units(),"\n")
print("Risk Products: ",sa.risk_products(),"\n")
print("Regional Reliability: ",sa.regional_reliability(),"\n")
print("Most Stable Product ID: ",sa.most_stable_product(),"\n")
print("After Return Normalization:\n", sa.normalize_returns(),"\n")
print("Stability Index:", sa.stability_index(),"\n")
print("Forecast Readiness:", sa.forecast_readiness(),"\n") 
print("Planning Priority:", sa.planning_priority()) 


Net Units: [[110 128 119 137 125]
 [ 65  72  69  71  73]
 [192 201 195 207 213]
 [ 40  43  49  45  48]
 [138 142 134 145 146]
 [224 233 229 237 243]] 

Risk Products:  [1, 3] 

Regional Reliability:  [128.16666666666666, 136.5, 132.5, 140.33333333333334, 141.33333333333334] 

Most Stable Product ID:  5 

After Return Normalization:
 [[110 128 119 137 125]
 [ 66  72  71  71  73]
 [192 201 195 207 213]
 [ 40  43  49  45  48]
 [138 142 134 146 146]
 [224 233 229 237 243]] 

Stability Index: [61.9, 35.3, 100.8, 22.5, 70.6, 116.6] 

Forecast Readiness: ['Moderate', 'Unstable', 'High', 'Unstable', 'Moderate', 'High'] 

Planning Priority: [5, 2, 4, 0, 1, 3]
