In [2]:
from abc import ABC, abstractmethod

class Father(ABC):
    def displ(self):
        print("Concrete Method")
    @abstractmethod
    def show(self):
        pass

class Child(Father):
    def show(self):
        print("Father abstract method")
        
c = Child()
c.displ()
c.show()

Concrete Method
Father abstract method


In [3]:
class Car(ABC):
    @abstractmethod
    def mileage(self):
        pass
    @abstractmethod
    def fuel(self):
        pass
    
class Suzuki(Car):
    def mileage(self):
        print("The mileage of car is 25kmpl")
    def fuel(self):
        print("The fuel type used is Petrol")
        
class Honda(Car):
    def mileage(self):
        print("The mileage of car is 22kmpl")
    def fuel(self):
        print("The fuel type used is CNG")        
        
class Hyundai(Car):
    def mileage(self):
        print("The mileage of car is 23kmpl")
    def fuel(self):
        print("The fuel type used is Diesel")
    def acc(self):
        print("It has all the accesories")
        
s = Suzuki()
h1 = Honda()
h2 = Hyundai()
s.mileage()
h1.mileage()
h2.mileage()
h2.acc()

The mileage of car is 25kmpl
The mileage of car is 22kmpl
The mileage of car is 23kmpl
It has all the accesories


In [10]:
# Create an abstract class named Shape.
# Create an abstract method named calculate_area for the Shape class.
# Create Two Classes named Rectangle and Circle which inherit Shape class.
# Create calculate_area method in Rectangle class. It should return the area of the rectangle object. (area of rectangle =
# (length * breadth))
# Create calculate_area method in Circle class. It should return the area of the circle object.
# (area of circle =πr^2))
# Create objects of Rectangle and Circle class.
# The python Program Should also check whether the area of one Rectangle object is greater
# than another rectangle object by overloading > operator.
# Execute the method resolution order of the Circle class.

from abc import ABC, abstractmethod

class Shape(ABC):
    @abstractmethod
    def calculate_area(self):
        pass
    
class Rectangle(Shape):
    def __init__(self,length,breadth):
        self.l = length
        self.b = breadth
    def calculate_area(self):
        self.area = self.l*self.b
        return self.area
    def __gt__(self,other):
        return self.calculate_area()>other.calculate_area()
        
class Circle(Shape):
    def __init__(self,r):
        self.r = r
    def calculate_area(self):
        self.area = 3.12*self.r*self.r
        return self.area
    
r1 = Rectangle(10,20)
r2 = Rectangle(20,30)
c = Circle(10)
a1 = r1.calculate_area()
a2 = r2.calculate_area()
print(a1,a2)
print(r1.__gt__(r2))
print(r1>r2)
print(r1<r2)
a3 = c.calculate_area()
print(a3)
print(Circle.mro())

200 600
False
False
True
312.0
[<class '__main__.Circle'>, <class '__main__.Shape'>, <class 'abc.ABC'>, <class 'object'>]


In [15]:
# Write a Python Program to Find the Net Salary of Employee using Inheritance.
# Create three Class Employee, Perks, NetSalary. Make an Employee class as an abstract class.
# Employee class should have methods for following tasks.
# - To get employee details like employee id, name and salary from user.
# - To print the Employee details.
# - return Salary.
# - An abstract method emp_id.
# Perks class should have methods for following tasks.
# - To calculate DA, HRA, PF.
# - To print the individual and total of Perks (DA+HRA-PF).
# Netsalary class should have methods for following tasks.
# - Calculate the total Salary after Perks.
# - Print employee detail also prints DA, HRA, PF and net salary.
# Note 1: DA-35%, HRA-17%, PF-12%
# Note 2: It is compulsory to create objects and demonstrating the methods with
# Correct output. Example:
# Employee ID: 1
# Employee Name: John
# Employee Basic Salary: 25000
# DA: 8750.0
# HRA: 4250.0
# PF: 3000.0
# Total Salary: 35000.0

from abc import ABC, abstractmethod

class Employee(ABC):
    def __init(self):
        self.employee_id = ""
        self.name = ""
        self.salary = 0
        
    def getDetails(self):
        self.employee_id = input("Enter Employee id : ")
        self.name = input("Enter Employee name : ")
        self.salary = int(input("Enter Employee salary : "))
    
    def printDetails(self):
        print(f"Employee id : {self.employee_id}")
        print(f"Employee name : {self.name}")
        print(f"Employee salary : {self.salary}")
        
    def returnSalary(self):
        return self.salary
    
class Perks(Employee):
    def __init__(self):
        self.da = 0
        self.hra = 0
        self.pf = 0
        self.basic = 0
        self.b = 0
    def C_da_hra_pf(self):
        self.basic = super().returnSalary()
        self.da = self.basic*0.35
        self.hra = self.basic*0.17
        self.pf = self.basic*0.12
        self.b = self.da+self.hra-self.pf
    def display(self):
        print(f"DA: {self.da}")
        print(f"HRA: {self.hra}")
        print(f"PF: {self.pf}")
        print(f"Total: {self.da+self.hra-self.pf}")
        
class NetSalary(Perks):
    def __init__(self):
        self.total = 0
    def C_total(self):
        self.total = self.basic+self.b
    def printTotalDetails(self):
        print(f"Employee id : {self.employee_id}")
        print(f"Employee name : {self.name}")
        print(f"Employee salary : {self.salary}")
        print(f"DA: {self.da}")
        print(f"HRA: {self.hra}")
        print(f"PF: {self.pf}")
        print(f"Total: {self.total}")
        
e = NetSalary()
e.getDetails()
e.C_da_hra_pf()
e.C_total()
e.printTotalDetails()

Enter Employee id : 1
Enter Employee name : Saumya
Enter Employee salary : 25000
Employee id : 1
Employee name : Saumya
Employee salary : 25000
DA: 8750.0
HRA: 4250.0
PF: 3000.0
Total: 35000.0


In [29]:
import numpy as np

arr1 = np.array([1,2,3,4])
print(arr1)
print(arr1.dtype)
print(arr1.itemsize)

arr2 = np.array([1,2.7,3.5,"a"])
print(arr2)
print(arr2.dtype)
print(arr2.itemsize)

arr3 = np.arange(10)
print(arr3)
print(arr3.dtype)
print(arr3.itemsize)

arr4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr4)
print(arr4.shape)
print(arr4.ndim)
arr5 = np.array([[1,2,3],[4,5.0,6],[7,"8",9]])
print(arr5)
arr6 = np.concatenate((arr4,arr5),axis=0)
print(arr6)

[1 2 3 4]
int32
4
['1' '2.7' '3.5' 'a']
<U32
128
[0 1 2 3 4 5 6 7 8 9]
int32
4
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
[['1' '2' '3']
 ['4' '5.0' '6']
 ['7' '8' '9']]
[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']
 ['1' '2' '3']
 ['4' '5.0' '6']
 ['7' '8' '9']]
